import { PromptCategory, PromptModel, AISettingsModel } from '../types/ai';

export const AI_CATEGORIES: { id: PromptCategory; label: string; icon: string }[] = [
  { id: 'Keluarga', label: 'Keluarga', icon: 'Users' },
  { id: 'Parenting', label: 'Parenting', icon: 'Heart' },
  { id: 'Keuangan', label: 'Keuangan', icon: 'Wallet' },
  { id: 'Makanan', label: 'Makanan & Menu', icon: 'Utensils' },
  { id: 'Kesehatan', label: 'Kesehatan', icon: 'Activity' },
  { id: 'Pendidikan', label: 'Pendidikan', icon: 'GraduationCap' },
  { id: 'Kalender', label: 'Jadwal & Agenda', icon: 'Calendar' },
  { id: 'Rumah', label: 'Rumah & Kebersihan', icon: 'Home' },
  { id: 'Mood', label: 'Mood & Harmoni', icon: 'Smile' },
  { id: 'Produktivitas', label: 'Produktivitas', icon: 'CheckSquare' },
  { id: 'Keamanan', label: 'Keamanan Darurat', icon: 'ShieldAlert' },
  { id: 'Memori', label: 'Memori & Foto', icon: 'Image' },
  { id: 'Asuransi', label: 'Asuransi & Proteksi', icon: 'FileText' },
];

export const DEFAULT_PROMPTS: PromptModel[] = [
  {
    id: 'p1',
    title: 'Ringkasan Hari Ini',
    description: 'Rangkuman agenda, tagihan, dan prioritas keluarga hari ini.',
    category: 'Keluarga',
    templateText: 'Tolong buatkan ringkasan agenda keluarga, pengingat penting, dan prioritas tugas untuk hari ini.',
    isFavorite: true,
    isPinned: true,
    isRecent: true,
    tags: ['ringkasan', 'harian', 'agenda'],
    quickCommand: '/summary',
  },
  {
    id: 'p2',
    title: 'Tips Parenting Modern',
    description: 'Panduan mendampingi anak secara positif dan empati.',
    category: 'Parenting',
    templateText: 'Bagaimana cara terbaik mendampingi anak umur 7-10 tahun saat belajar membagi waktu antara gadget dan tugas sekolah?',
    isFavorite: true,
    isPinned: false,
    isRecent: true,
    tags: ['parenting', 'anak', 'edukasi'],
  },
  {
    id: 'p3',
    title: 'Rencana Menu Mingguan',
    description: 'Rekomendasi variasi masakan sehat, hemat, dan bergizi seimbang.',
    category: 'Makanan',
    templateText: 'Tolong susunkan rencana menu makan siang & malam selama 7 hari untuk 4 porsi dengan anggaran terjangkau.',
    isFavorite: true,
    isPinned: true,
    isRecent: true,
    tags: ['resep', 'menu', 'makanan', 'mingguan'],
    quickCommand: '/meal',
  },
  {
    id: 'p4',
    title: 'Ide Aktivitas Keluarga Akhir Pekan',
    description: 'Inspirasi rekreasi edukatif dan bonding keluarga di rumah atau luar ruangan.',
    category: 'Keluarga',
    templateText: 'Berikan 5 ide aktivitas outdoor & indoor menyenangkan untuk akhir pekan bersama anak dan pasangan.',
    isFavorite: false,
    isPinned: false,
    isRecent: false,
    tags: ['liburan', 'bonding', 'akhir pekan'],
  },
  {
    id: 'p5',
    title: 'Pengingat Tagihan & Anggaran',
    description: 'Audit pengeluaran bulanan dan pengingat tanggal jatuh tempo.',
    category: 'Keuangan',
    templateText: 'Bantu cek alokasi keuangan keluarga 50/30/20 dan susun daftat pengingat tagihan bulanan.',
    isFavorite: true,
    isPinned: false,
    isRecent: true,
    tags: ['keuangan', 'anggaran', 'tagihan'],
    quickCommand: '/finance',
  },
  {
    id: 'p6',
    title: 'Motivasi & Afirmasi Hari Ini',
    description: 'Kalimat hangat untuk menjaga keharmonisan dan semangat anggota keluarga.',
    category: 'Mood',
    templateText: 'Berikan pesan motivasi hangat dan tips menjaga komunikasi harmonis suami istri hari ini.',
    isFavorite: false,
    isPinned: false,
    isRecent: true,
    tags: ['motivasi', 'mood', 'harmoni'],
    quickCommand: '/mood',
  },
  {
    id: 'p7',
    title: 'Rencana Belajar Anak',
    description: 'Jadwal dan metode belajar efektif tanpa paksaan.',
    category: 'Pendidikan',
    templateText: 'Buatkan rencana jadwal belajar dan latihan soal harian yang menyenangkan untuk persiapan ujian anak.',
    isFavorite: false,
    isPinned: false,
    isRecent: false,
    tags: ['sekolah', 'belajar', 'ujian'],
  },
  {
    id: 'p8',
    title: 'Pemeriksaan Kesehatan & Nutrisi',
    description: 'Panduan pola hidup sehat, suplemen, dan pencegahan demam.',
    category: 'Kesehatan',
    templateText: 'Apa saja tips meningkatkan daya tahan tubuh anak dan orang tua di musim hujan?',
    isFavorite: false,
    isPinned: false,
    isRecent: false,
    tags: ['kesehatan', 'nutrisi', 'imunitas'],
    quickCommand: '/health',
  },
  {
    id: 'p9',
    title: 'Sinkronisasi Kalender Acara',
    description: 'Kelola jadwal arisan, dokter, les, dan kerja.',
    category: 'Kalender',
    templateText: 'Bantu tata ulang jadwal mingguan agar tidak bentrok antara rapat kantor dan acara sekolah anak.',
    isFavorite: false,
    isPinned: false,
    isRecent: false,
    tags: ['jadwal', 'kalender', 'agenda'],
    quickCommand: '/calendar',
  },
  {
    id: 'p10',
    title: 'Prosedur Keamanan & Kontak Darurat',
    description: 'Panduan tanggap bencana dan langkah darurat rumah tangga.',
    category: 'Keamanan',
    templateText: 'Tuliskan daftar checklist keamanan rumah sebelum ditinggal bepergian dan nomor darurat keluarga.',
    isFavorite: false,
    isPinned: false,
    isRecent: false,
    tags: ['darurat', 'keamanan', 'rumah'],
  },
];

export const QUICK_COMMANDS = [
  { command: '/summary', description: 'Tampilkan ringkasan aktivitas & agenda hari ini' },
  { command: '/reminder', description: 'Buat pengingat tagihan / tugas keluarga baru' },
  { command: '/calendar', description: 'Lihat preview & rekomendasi jadwal mingguan' },
  { command: '/meal', description: 'Rekomendasi resep masakan & rencana menu harian' },
  { command: '/health', description: 'Tips kesehatan & rekomendasi imunitas' },
  { command: '/finance', description: 'Checklist anggaran dan laporan singkat pengeluaran' },
  { command: '/mood', description: 'Cek suasana hati & pesan penguat harmoni keluarga' },
  { command: '/help', description: 'Panduan lengkap cara menggunakan AI Family Assistant' },
];

export const DEFAULT_AI_SETTINGS: AISettingsModel = {
  aiEnabled: true,
  memoryEnabled: true,
  contextEnabled: true,
  personalizationEnabled: true,
  provider: 'gemini',
  modelName: 'gemini-3.6-flash',
  responseLength: 'sedang',
  language: 'id',
  tone: 'ramah',
  creativity: 'seimbang',
  autoScroll: true,
  showSystemPrompt: true,
  saveOffline: true,
};
