import { DashboardCardItem } from '../types/dashboard';

export const APP_CONFIG = {
  name: 'FamilyAI Hub Indonesia',
  edition: 'Mobile Web Edition',
  version: '1.0.0 (Phase 1)',
  supportedBreakpoints: [360, 375, 390, 414, 430, 480, 600, 768],
};

export const ONBOARDING_SLIDES = [
  {
    id: 1,
    title: 'Selamat Datang di FamilyAI Hub',
    subtitle: 'Ekosistem Digital Cerdas Pertama untuk Harmoni Keluarga Indonesia',
    description: 'Menghubungkan seluruh anggota keluarga dalam satu aplikasi mobile web yang intuitif, aman, dan penuh kehangatan.',
    gradient: 'from-blue-600 via-indigo-600 to-teal-500',
    icon: 'HeartHandshake',
  },
  {
    id: 2,
    title: 'Semua Keluarga Dalam Satu Aplikasi',
    subtitle: 'Kelola Mood, Keuangan, Kesehatan & Pendidikan',
    description: 'Satu hub terpusat untuk memantau kesehatan rutin, anggaran rumah tangga, jadwal les anak, hingga menu makanan bernutrisi.',
    gradient: 'from-teal-600 via-emerald-600 to-cyan-500',
    icon: 'Users',
  },
  {
    id: 3,
    title: 'Kecerdasan AI untuk Keluarga',
    subtitle: 'Asisten Pintar Berbasis Kecerdasan Buatan',
    description: 'Mendapatkan rekomendasi harian, pengingat otomatis, dan solusi keluarga dengan teknologi AI terdepan.',
    gradient: 'from-indigo-600 via-purple-600 to-blue-500',
    icon: 'Sparkles',
  },
  {
    id: 4,
    title: 'Mulai Sekarang',
    subtitle: 'Wujudkan Keluarga Indonesia Cerdas & Sejahtera',
    description: 'Bergabunglah dengan ribuan keluarga Indonesia yang telah mempererat keharmonisan bersama FamilyAI Hub.',
    gradient: 'from-blue-600 via-cyan-600 to-teal-600',
    icon: 'ShieldCheck',
  },
];

export const INITIAL_DASHBOARD_CARDS: DashboardCardItem[] = [
  {
    id: 'mood',
    title: 'Mood & Harmoni',
    subtitle: 'Suasana Hati Keluarga Hari Ini',
    iconName: 'Smile',
    badgeText: 'Sangat Baik',
    gradient: 'from-amber-500/20 to-orange-500/10 dark:from-amber-500/30 dark:to-orange-500/15',
    accentColor: '#F59E0B',
    metrics: [
      { label: 'Indeks Harmoni', value: '94%' },
      { label: 'Energi Positif', value: 'Tinggi' },
    ],
    summary: 'Keluarga Pratama hari ini dalam kondisi penuh kehangatan & keceriaan.',
    recentItems: [
      'Ibu: Merasa bahagia setelah senam pagi',
      'Ayah: Fokus & optimis menyelesaikan pekerjaan',
      'Anak (Budi): Antusias menyambut akhir pekan',
    ],
  },
  {
    id: 'health',
    title: 'Kesehatan & Medis',
    subtitle: 'Rekam Medis & Jadwal Check-up',
    iconName: 'Activity',
    badgeText: '2 Pengingat',
    gradient: 'from-emerald-500/20 to-teal-500/10 dark:from-emerald-500/30 dark:to-teal-500/15',
    accentColor: '#10B981',
    metrics: [
      { label: 'Vitamin Harian', value: 'Selesai' },
      { label: 'Jadwal Dokter', value: 'Besok, 09:00' },
    ],
    summary: 'Keluarga sehat terawat dengan catatan imunisasi dan vitamin teratur.',
    recentItems: [
      'Pemeriksaan rutin BPJS / Klinik Pratama besok',
      'Pemberian vitamin C Budi jam 19:00',
      'Hasil cek tensi Ayah: 118/78 mmHg (Normal)',
    ],
  },
  {
    id: 'finance',
    title: 'Keuangan Keluarga',
    subtitle: 'Anggaran & Dompet Rumah Tangga',
    iconName: 'Wallet',
    badgeText: 'Terkendali',
    gradient: 'from-blue-500/20 to-indigo-500/10 dark:from-blue-500/30 dark:to-indigo-500/15',
    accentColor: '#2563EB',
    metrics: [
      { label: 'Sisa Anggaran', value: 'Rp 6.450.000' },
      { label: 'Tabungan Bulan Ini', value: '82% Target' },
    ],
    summary: 'Pengeluaran mingguan berada di dalam batas toleransi aman anggaran.',
    recentItems: [
      'Belanja bulanan sembako: Rp 1.200.000',
      'Pembayaran listrik & internet PLN/Indihome: Lunas',
      'Alokasi dana darurat keluarga: Rp 500.000',
    ],
  },
  {
    id: 'education',
    title: 'Pendidikan & PR',
    subtitle: 'Jadwal Belajar & Prestasi Anak',
    iconName: 'GraduationCap',
    badgeText: 'PR Budi',
    gradient: 'from-purple-500/20 to-pink-500/10 dark:from-purple-500/30 dark:to-pink-500/15',
    accentColor: '#8B5CF6',
    metrics: [
      { label: 'PR Belum Selesai', value: '1 Tugas' },
      { label: 'Jadwal Les Matematika', value: 'Kamis 16:00' },
    ],
    summary: 'Progres pendidikan anak terpantau dengan dukungan bimbingan AI.',
    recentItems: [
      'PR Matematika Budi: Bab 4 Geometri (Dikumpulkan Jumat)',
      'Nilai Ujian IPA Sisi: 92 (Sangat Baik)',
      'E-book cerita rakyat Indonesia dibaca 2x',
    ],
  },
  {
    id: 'meal',
    title: 'Menu & Nutrisi',
    subtitle: 'Rekomendasi Resep Sehat Indonesia',
    iconName: 'Utensils',
    badgeText: 'Rekomendasi AI',
    gradient: 'from-rose-500/20 to-orange-500/10 dark:from-rose-500/30 dark:to-orange-500/15',
    accentColor: '#F43F5E',
    metrics: [
      { label: 'Makan Malam', value: 'Sop Buntut Sehat' },
      { label: 'Target Kalori', value: '2.100 kkal' },
    ],
    summary: 'Rencana variasi resep nusantara bergizi imbang rendah kolesterol.',
    recentItems: [
      'Makan Siang: Ayam Bakar Bumbu Rujak + Capcay',
      'Makan Malam: Sop Buntut Wortel Kentang Organik',
      'Cemilan Sore: Pisang Rebus & Teh Hangat',
    ],
  },
  {
    id: 'calendar',
    title: 'Kalender Acara',
    subtitle: 'Agenda & Arisan Keluarga Besar',
    iconName: 'Calendar',
    badgeText: '3 Agenda',
    gradient: 'from-cyan-500/20 to-blue-500/10 dark:from-cyan-500/30 dark:to-blue-500/15',
    accentColor: '#06B6D4',
    metrics: [
      { label: 'Acara Terdekat', value: 'Minggu ini' },
      { label: 'Arisan RT', value: 'Sabtu, 19:30' },
    ],
    summary: 'Sinkronisasi agenda harian seluruh anggota keluarga tanpa bentrok.',
    recentItems: [
      'Arisan Keluarga Besar di Rumah Tante Rina (Minggu 10:00)',
      'Jadwal Service Mobil Avanza (Sabtu 09:00)',
      'Ulang Tahun Nenek (15 Agustus)',
    ],
  },
  {
    id: 'safety',
    title: 'Keamanan & Lokasi',
    subtitle: 'Zona Aman Anggota Keluarga',
    iconName: 'Shield',
    badgeText: 'Safe Zone',
    gradient: 'from-teal-500/20 to-emerald-500/10 dark:from-teal-500/30 dark:to-emerald-500/15',
    accentColor: '#14B8A6',
    metrics: [
      { label: 'Status Anggota', value: '4/4 Aman' },
      { label: 'Budi (Anak)', value: 'Di Sekolah' },
    ],
    summary: 'Sistem deteksi zona lokasi aman aktif & terlindungi 24 jam.',
    recentItems: [
      'Ayah: Sampai di kantor Gedung Cyber',
      'Ibu: Berada di rumah (Safe Zone)',
      'Budi: Berada di SMP Negeri 1 Jakarta',
    ],
  },
  {
    id: 'smarthome',
    title: 'Rumah Pintar',
    subtitle: 'Kontrol Perangkat IoT Rumah',
    iconName: 'Home',
    badgeText: '4 Aktif',
    gradient: 'from-indigo-500/20 to-violet-500/10 dark:from-indigo-500/30 dark:to-violet-500/15',
    accentColor: '#6366F1',
    metrics: [
      { label: 'Lampu Utama', value: 'Hemat Energi' },
      { label: 'AC Kamar Utama', value: '24°C Auto' },
    ],
    summary: 'Pengaturan daya listrik otomatis efisien dan hemat energi.',
    recentItems: [
      'CCTV Teras Depan: Deteksi Gerakan Normal',
      'Kunci Pintar Pintu Depan: Terkunci Rapat',
      'Penyiram Tanaman Otomatis: Aktif Jam 17:00',
    ],
  },
  {
    id: 'memory',
    title: 'Galeri Kenangan',
    subtitle: 'Album Foto & Momen Berharga',
    iconName: 'Image',
    badgeText: '350 Foto',
    gradient: 'from-fuchsia-500/20 to-pink-500/10 dark:from-fuchsia-500/30 dark:to-pink-500/15',
    accentColor: '#D946EF',
    metrics: [
      { label: 'Album Baru', value: 'Liburan Bali 2026' },
      { label: 'Kilas Balik', value: '3 Tahun Lalu' },
    ],
    summary: 'Arsip kenangan indah tersimpan rapi dan dapat diakses bersama.',
    recentItems: [
      'Album: Ulang Tahun Budi ke-12',
      'Video: Momen Pementasan Seni Sekolah Sisi',
      'Foto: Makan Bersama Akhir Pekan Kemarin',
    ],
  },
  {
    id: 'ai',
    title: 'Asisten AI Keluarga',
    subtitle: 'Konsultasi & Solusi Harmoni AI',
    iconName: 'Sparkles',
    badgeText: 'Siap 24/7',
    gradient: 'from-sky-500/20 to-blue-600/10 dark:from-sky-500/30 dark:to-blue-600/15',
    accentColor: '#0284C7',
    metrics: [
      { label: 'Model AI', value: 'Gemini Family 2.5' },
      { label: 'Respons Rata-rata', value: '< 1 Detik' },
    ],
    summary: 'Asisten cerdas siap memberi saran resep, pengingat, dan ide kegiatan.',
    recentItems: [
      '"Berikan ide aktivitas keluarga di hari Minggu"',
      '"Buatkan daftar belanjaan sayur hemat 100 ribu"',
      '"Bagaimana tips mendampingi anak saat belajar IPA?"',
    ],
  },
];
